### ISSUE TITLE
How’s it going?

### ISSUE THREAD

**Issue by danbruder** [resamplr/resamplr-web#6]
I have been following the project wondering if you still like the rust/elm combo?

**Comment by piedoom** [comment]
I've had this project on hold for a bit until rocket has time to mature (mainly through multipart uploads) as I'm not much of a Rust guru.  Elm has changed a bit for the better too, it's new Browser API is much better for SPAs, however I still find it to be a little too verbose/boilerplate-ish.  I've been looking into PureScript but I'm not a fan of how hard it depends on NPM tooling (not to mention that level of functional programming is a little beyond my reach).  

Being said, I still think Rocket & Elm are best candidates to this project (besides perhaps a pure rust solution like yew).  Actix is nice, but Rocket still seems most ergonomic for my use case.

In the more immediate future, I am thinking of a more service-based approach.  It would be nice to split out the audio upload/processing part of the application in Rust a part at a time instead of directly switch the entire codebase at once.

**Comment by danbruder** [comment]
Nice - thanks for the reply!
